theme: jekyll-theme-cayman
title: NanoLinks - The Ultimate Link Guide
description: A curated URL guide to find anything about Nano; The fast, free and green digital currency for the real world! Links to Information, Education, Markets, Merchants, Exchanges, Wallets, Videos, Media, Applications, Development tools, Source Code and Entertainment. A cryptocurrency library.
url: https://nanolinks.info
author: Joohansson
favicon: src/favicon.ico
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
google_analytics: UA-113887773-2
social:
  name: Joohansson
  links:
    - https://github.com/Joohansson
    - https://www.reddit.com/user/Joohansson/
