theme: jekyll-theme-cayman
title: NanoLinks
description: A curated URL guide to find anything about Nano; The fast, feeless and green digital currency! Links to Information, Education, Markets, Merchants, Exchanges, Wallets, Videos, Media, News, Applications, Development tools, Source Code, Entertainment and Services.
url: https://nanolinks.info
author: Joohansson
exclude: ["README.md", "LICENSE"]
markdown: kramdown
plugins:
  - jekyll-seo-tag
google_analytics: UA-113887773-2
social:
  name: Joohansson
  links:
    - https://github.com/Joohansson
    - https://www.reddit.com/user/Joohansson/
